#!/bin/sh

# läs in conf
. /etc/inst.conf

if [ "$1" = "-c" ]
then

for pkg in $*
do
if [ "$pkg" != "-c" ]
then
prog=$( awk NR=="$pkg" /etc/inst_list )
echo "Installing $prog"
pkg_add -v $pkg_site/$prog
fi
done

else

for pkg in $*
do
prog=$( grep $pkg /etc/inst_list )
echo "Installing $prog"
pkg_add -v $pkg_site/$prog
done

fi
