arch="$(uname -m)"
ver="$(uname -r)"
os="$(uname -s)"
pkg_site="ftp://ftp.su.se/pub/$os/$ver/packages/$arch"

# in freebsd, use:
# ftp://ftp.sunet.se/pub/$os/ports/$arch/**  *not finished yet*

#in NetBSD use:
# ftp://ftp.netbsd.se/pkgsrc/packages/$os/$arch/$ver/All/
